### ISSUE TITLE
[Request]: CLEAR

### ISSUE THREAD

**Issue by gregmichael** [joshuah345/iosjbdetectold#1]
### App to request

Clear

### App Store link

https://apps.apple.com/us/app/clear-fast-touchless-access/id1436333504

### App version

1.37.0

### Jailbreak

unc0ver 8.0.2

### Bypass tried

A-Bypass & Vnode

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
Did the bypass you tried work?

**Comment by gregmichael** [comment]
> Did the bypass you tried work?

No, they didn't

**Comment by joshuah345** [comment]
CLEAR has somewhat advanced jb detection, so there currently isn't a bypass for it
