### ISSUE TITLE
[Request]: Uber driver 

### ISSUE THREAD

**Issue by Damion675** [joshuah345/iosjbdetectold#10]
### App to request

Uber-driver

### App Store link

https://apps.apple.com/us/app/uber-driver-drive-deliver/id1131342792

### App version

4.333.10001

### Jailbreak

Fugu 14+unc0ver

### Bypass tried

Vnode bypass works for this app

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beerpiss** [comment]
handled by 63733c911d6d4429e3a858388dbd4384f765556f

**Comment by beer-psi** [comment]
handled by 63733c911d6d4429e3a858388dbd4384f765556f
