### ISSUE TITLE
[Request]:LibreLink

### ISSUE THREAD

**Issue by jassm93** [joshuah345/iosjbdetectold#11]
### App to request

FreeStyle LibreLink

### App Store link

https://apps.apple.com/us/app/freestyle-librelink-us/id1325992472

### App version

2.5.3

### Jailbreak

unc0ver

### Bypass tried

No tool worked, an important app for diabetics

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
![bypass list](https://share.beerpsi.me/raw/hvb0cr96.png)

Did you try all of these bypasses? If you have and none is working, I'll have to add LibreLink as `no bypass known`.

**Comment by beer-psi** [comment]
Also it looks like you're probably out of luck:
> A kernel bypass is probably needed for this, they're using kernel syscalls to detect a jailbreak / rootfs remount. Not much I can do to get around it unfortunately. Kind of ridiculous really for a glucose monitoring app

\- level3tjg on [this thread](https://old.reddit.com/r/jailbreak/comments/m2c1op/help_freestyle_librelink_crashing_after_unc0ver/) on Reddit

I'm sorry I can't really help, we're just webdevs/tinkerers.

**Comment by jassm93** [comment]
Yes, all tools have been tried, and the application refuses
