### ISSUE TITLE
[Request]: Yoti

### ISSUE THREAD

**Issue by alemosobh** [joshuah345/iosjbdetectold#12]
### App to request

Yoti

### App Store link

https://apps.apple.com/eg/app/yoti-your-digital-identity/id983980808

### Jailbreak

Unc0ver 8.0.2

### Bypass tried

Nothing work with this app

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
![bypass list](https://share.beerpsi.me/raw/hvb0cr96.png)

Did you try all of these bypasses? If you have and none is working, I'll have to add Yoti as `no bypass known`.
