### ISSUE TITLE
[Request]:alexbank mobile banking

### ISSUE THREAD

**Issue by Lodava** [joshuah345/iosjbdetectold#15]
### App to request

ALEXBANK Mobile Banking

### App Store link

https://apps.apple.com/eg/app/alexbank-mobile-banking/id1246718290

### App version

5.0.288

### Jailbreak

Unc0ver

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
![bypass list](https://share.beerpsi.me/raw/hvb0cr96.png)

Did you try all of these bypasses? If you have and none is working, I'll have to add the app as `no bypass known`.

**Comment by joshuah345** [comment]
vnodebypass is working for this app. please try bypasses before opening an issue.
