### ISSUE TITLE
[Request]: FAB Mobile Banking

### ISSUE THREAD

**Issue by sss8911** [joshuah345/iosjbdetectold#16]
### App to request

FAB MOBILE BANKING

### App Store link

https://apps.apple.com/ae/app/fab-mobile-banking/id1383237548

### App version

10.0.63

### Jailbreak

Uncover

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [x] Hestia
- [x] Shadow
- [X] HideJB
- [x] KernBypass (iOS 12.0 - 14.2)
- [x] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
There currently isn't a working bypass for this app.

**Comment by sss8911** [comment]
There's one way only on version 10.055 by hidejb ,i use it
