### ISSUE TITLE
[Request]: OTP Bank

### ISSUE THREAD

**Issue by AndrisBorbas** [joshuah345/iosjbdetectold#17]
### App to request

OTP Bank HU

### App Store link

https://apps.apple.com/hu/app/otp-bank-hu/id1403268557

### App version

2.49.1

### Jailbreak

Unc0ver + Fugu

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

I also tried Libertas which also didn't work.

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by beer-psi** [comment]
@joshuah345 can you look into this? as expected no hooking bypasses (A-Bypass, Shadow, HideJB) are working for me

vnode also isn't working

**Comment by joshuah345** [comment]
hooking seems to cause the app to crash. Hestia's compatibility mode lets it launch but doesn't bypass detection.

Frida can't even attach to it

**Comment by beer-psi** [comment]
guess the app will be marked as "no known bypass" for now

**Comment by beer-psi** [comment]
Closed by commit 2abd80aeaa62d811b446a4362bf6444b02a69fcd
