### ISSUE TITLE
[Request]: Kuwait Mobile ID

### ISSUE THREAD

**Issue by firefighterq8e** [joshuah345/iosjbdetectold#19]
### App to request

kuwait mobile id هويتي

### App Store link

https://apps.apple.com/us/app/kuwait-mobile-id-%D9%87%D9%88%D9%8A%D8%AA%D9%8A/id1449712307

### App version

1.9.0

### Jailbreak

Unc0ver

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [ ] Hestia
- [X] Shadow
- [ ] HideJB
- [X] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Nothing

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
#7 already exists, closing as duplicate.
