### ISSUE TITLE
[Request]: Nintendo Switch Online

### ISSUE THREAD

**Issue by ccdffddfddfdsfedeee** [joshuah345/iosjbdetectold#20]
### App to request

Nintendo Switch Online

### App Store link

https://apps.apple.com/us/app/nintendo-switch-online/id1234806557

### App version

1.14.0

### Jailbreak

Checkra1n

### Bypass tried

- [X] A-Bypass
- [ ] Liberty Lite (Beta)
- [ ] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Nintendo Switch Online currently doesn't have a bypass. Refer to the note at the top of the app list regarding nintendo apps.
