### ISSUE TITLE
[Request]: Southwest Airlines

### ISSUE THREAD

**Issue by naquadah007** [joshuah345/iosjbdetectold#22]
### App to request

Southwest

### App Store link

https://apps.apple.com/us/app/southwest-airlines/id344542975

### App version

8.12

### Jailbreak

Unc0ver

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Hestia

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Added, Thanks.
