### ISSUE TITLE
[Request]: BestBuy Connect

### ISSUE THREAD

**Issue by naquadah007** [joshuah345/iosjbdetectold#23]
### App to request

BestBuy Connect

### App Store link

~~https://apps.bestbuy.com/app/1e4f8590-53ea-4aa9-8f7f-aa5c68000271/details~~
https://apps.apple.com/us/app/best-buy-connect/id1577419496

### App version

22.1.1

### Jailbreak

Unc0ver

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [X] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

None

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
The link you sent to the app is for Best Buy associates (it's internal only). Please use App Store links when you can: https://apps.apple.com/us/app/best-buy-connect/id1577419496

So far, i don't see any jailbreak detection in this app, but it would help if you send an ipa for the one you have to make sure.

you can generate ipas using bfdecrypt (available from https://level3tjg.me/repo)

**Comment by naquadah007** [comment]
Here is a google drive link to the Best Buy Connect IPA. Thank you!

https://drive.google.com/file/d/1jaEglNNjdfKfRmN20pqwSBpgn2ZwspNQ/view?usp=sharing



Sincerely,
Douglas Dixon

**Comment by joshuah345** [comment]
Thanks. the app store variant seems to just have the detection missing outright. the one you sent crashes due to detection.

vnodebypass isn't working either, so i'll list it as having no bypass at the moment.
