### ISSUE TITLE
[Request]: Battle.net

### ISSUE THREAD

**Issue by naquadah007** [joshuah345/iosjbdetectold#24]
### App to request

Battle.net

### App Store link

https://apps.apple.com/us/app/battle-net/id1241040030

### App version

1.16.0

### Jailbreak

Unc0ver

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [X] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Choicy

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Choicy/libhooker-configurator isn't required for the app to run. You most likely have a tweak that's causing the app to crash. However, i will still note this.
