### ISSUE TITLE
[Request]: AcuraLink

### ISSUE THREAD

**Issue by naquadah007** [joshuah345/iosjbdetectold#25]
### App to request

Acuralink

### App Store link

https://apps.apple.com/us/app/acuralink/id610964308

### App version

4.5.0

### Jailbreak

Unc0ver

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [X] Shadow
- [ ] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

None

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Works fine with Shadow. Use the [recommended configuration](https://bypass.beerpsi.me/#/tools/tweaks?id=shadow#/tools/tweaks?id=shadow#/tools/tweaks?id=shadow)
