### ISSUE TITLE
[Request]: Tangerine

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [joshuah345/iosjbdetectold#26]
### App to request
 Tangerine
### App Store link
https://apps.apple.com/us/app/tangerine-self-care-goals/id1468882685
### App version
3.7.4
### Jailbreak and iOS version
checkra1n, iOS 14.7.1
### Bypass tried
- Liberty Lite
- Shadow
### Which worked
n/a
### Checklist submission
The app is missing from the table, or bypasses are not working anymore., I have checked through all open issues and none matched my app., I have tried at least one bypass before submission.

**Comment by beer-psi** [comment]
Closed because the app doesn't have detection, it's just problematic.

**Comment by beer-psi** [comment]
Resolved by commit b82c9e904899b20bf199b528164be052f57062ce
