### ISSUE TITLE
[Request]: oddmar

### ISSUE THREAD

**Issue by Rebel4050** [joshuah345/iosjbdetectold#3]
### App to request

oddmar

### App Store link

https://apps.apple.com/sa/app/oddmar/id1247397901?l=ar

### App version

1.1.02

### Jailbreak

unc0ver fugu14 14.5.1 iphone11

### Bypass tried

Nothing worked

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
Closed, duplicate of #2
