### ISSUE TITLE
[Request]: Keurig

### ISSUE THREAD

**Issue by Deltakal** [joshuah345/iosjbdetectold#30]
### App to request

Keurig

### App Store link

https://apps.apple.com/us/app/id1200578231

### App version

1.2143.0

### Jailbreak

Unc0ver

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [ ] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Working with A-Bypass
