### ISSUE TITLE
[Request]: stc pay

### ISSUE THREAD

**Issue by adamfernn** [joshuah345/iosjbdetectold#31]
### App to request

Stcpay 

### App Store link

https://apps.apple.com/sa/app/stc-pay/id1364197140

### App version

Any

### Jailbreak

Unc0ver

### Bypass tried

- [ ] A-Bypass
- [ ] Liberty Lite (Beta)
- [ ] Hestia
- [ ] Shadow
- [ ] HideJB
- [ ] KernBypass (iOS 12.0 - 14.2)
- [ ] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
We forgot to add this app from the old spreadsheet. There currently isn't a bypass for it.
