### ISSUE TITLE
[Request]: Freecharge: Recharge, Bill Pay

### ISSUE THREAD

**Issue by goodboydheeraj** [joshuah345/iosjbdetectold#33]
### App to request

Freecharge

### App Store link

https://apps.apple.com/in/app/freecharge-payments-finance/id877495926

### App version

4.9.8

### Jailbreak

Odysseyra1n

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [X] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [ ] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

No known bypass for this app as of now. A-Bypass and FlyJB used to work fine with this app but now none of the bypasses are working including vnodebypass!

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Hestia is working.
- Enable image check patches
- Disable Compatibility mode

> Tested with unc0ver on iOS 14.8

**Comment by joshuah345** [comment]
Shadow is working as well.

**Comment by joshuah345** [comment]
Apparently, there seems to be issues on libhooker-based jbs (specifically odysseyra1n). @beerpiss can you test pls

**Comment by beer-psi** [comment]
libhooker stable (v1.6.3) seems to be problematic with hooking bypasses (Hestia, Shadow, etc.), but upgrading to 1.6.9b2 (from https://repo.theodyssey.dev/libhooker-beta) works. There should probably be a notice in the docs for this.

Both Hestia and Shadow works with the recommended settings on libhooker 1.6.9b2.
