### ISSUE TITLE
[Request]: SBI Card

### ISSUE THREAD

**Issue by goodboydheeraj** [joshuah345/iosjbdetectold#34]
### App to request

SBI Card

### App Store link

https://apps.apple.com/in/app/sbi-card/id694549848

### App version

7.3.11

### Jailbreak

Odysseyra1n

### Bypass tried

- [X] A-Bypass
- [X] Liberty Lite (Beta)
- [X] Hestia
- [ ] Shadow
- [ ] HideJB
- [X] KernBypass (iOS 12.0 - 14.2)
- [X] vnodebypass
- [X] Disabling tweak injection with Choicy or libhooker-configurator

### Which bypass worked?

Only vnodebypass is working for this app as of the latest v7.3.11. Would like to have a different bypass other than vnode

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.
- [X] I have tried at least one bypass before submission.

**Comment by beer-psi** [comment]
This issue form is for suggesting new bypasses, or reporting that old ones doesn't work anymore. It is not for actually requesting new bypasses. For that, you should be on the [r/TweakBounty subreddit](https://reddit.com/r/TweakBounty).
