### ISSUE TITLE
[Google Forms Request]: MyHyundai with BlueLink

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [joshuah345/iosjbdetectold#36]
### Bypass requested from Google Forms
Response ID: 11
### App to request
 MyHyundai with BlueLink
### App Store link
https://apps.apple.com/us/app/myhyundai-with-bluelink/id893514610
### App version
5.0.2
### Jailbreak and iOS version
Unc0ver 14.8
### Bypass tried
- A-Bypass
- Liberty Lite
- HyundaiBypass
### Which worked
A-Bypass - I reached out to HyundaiBypass and he said he will push an update when he gets his hands on a 14.8 jailbroken device 
### Checklist submission
- The app is missing from the tabl
- or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Hestia and Shadow (with slight configuration) also working.
