### ISSUE TITLE
[Google Forms Request]: GETTR

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [joshuah345/iosjbdetectold#39]
### Bypass requested from Google Forms
Response ID: 14
### App to request
 GETTR
### App Store link
https://apps.apple.com/us/app/gettr-a-marketplace-of-ideas/id1571619156
### App version
1.3.1
### Jailbreak and iOS version
unc0ver, iOS 14.8
### Bypass tried
- A-Bypass
### Which worked
A-Bypass: May need to enable "Enforce DYLD Hook"
### Checklist submission
- The app is missing from the table, or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
A-Bypass is working. no need to enforce dyld hook
Shadow and Hestia confirmed as well
