### ISSUE TITLE
[Request]: HBTF New Mobile Banking

### ISSUE THREAD

**Issue by Qashmaros** [joshuah345/iosjbdetectold#4]
### App to request

Hbtf new mobile banking

### App Store link

https://apps.apple.com/us/app/hbtf-new-mobile-banking/id1467891225

### App version

1.1.7

### Jailbreak

Uncover

### Bypass tried

No

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
resolved by 183db61c3adb2b686c1cd21895cc576a0e58edfb

**Comment by joshuah345** [comment]
Hestia works for this app
Toggle every patch and compatibility mode.
