### ISSUE TITLE
[Google Forms Request]: CorTrust Mobiliti

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [joshuah345/iosjbdetectold#40]
### Bypass requested from Google Forms
Response ID: 15
### App to request
 CorTrust Mobiliti
### App Store link
https://apps.apple.com/us/app/cortrust-mobiliti/id943218305
### App version
21.2.70
### Jailbreak and iOS version
unc0ver 14.8
### Bypass tried
- HideJB
### Which worked
HideJB
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment]
Can't confirm HideJB (or shadow)

> also on unc0ver on iOS 14.8

**Comment by joshuah345** [comment]
Working with A-Bypass, however
