### ISSUE TITLE
[Google Forms Request]: Bolt

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [joshuah345/iosjbdetectold#42]
### Bypass requested from Google Forms
Response ID: 16
### App to request
 Bolt
### App Store link
https://apps.apple.com/us/app/bolt-fast-affordable-rides/id675033630
### App version
The jailbreak works on any version
### Jailbreak and iOS version
Odysseyra1n Ios 14.7.1
### Bypass tried
- A-Bypass
- Liberty Lite
- Shadow
- HideJB
- Disabling tweak injection with Choicy or libhooker-configurator
### Which worked
Disabling Tweak injection with libhooker-configurator worked
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by beer-psi** [comment]
Migrated to https://github.com/hekatos/manifests/issues/1
