### ISSUE TITLE
[Request]: SBI Card

### ISSUE THREAD

**Issue by goodboydheeraj** [joshuah345/iosjbdetectold#5]
### App to request

SBI Card

### App Store link

https://apps.apple.com/in/app/sbi-card/id694549848

### App version

7.3.11

### Jailbreak

Checkra1n, Unc0ver

### Bypass tried

Worked with Kernbypass 0.0.5 until v7.3.9. The bypass on the latest version of the app now only works with vnodebypass.

iOS 13.3.1(7 Plus) on checkra1n and iOS  14.3(Kernbypass won’t work in this version) on Unc0ver(A14)

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
added in 0fbf7a376a3c43ecf6a203cd797030888bda2313
