### ISSUE TITLE
[Request]: HSBC UK

### ISSUE THREAD

**Issue by Auraaaaaaaa** [joshuah345/iosjbdetectold#6]
### App to request

HSBC UK

### App Store link

https://apps.apple.com/gb/app/hsbc-uk-mobile-banking/id1220329065

### App version

3.15.1

### Jailbreak

Taurine

### Bypass tried

VNODEBYPASS 

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
HSBC apps are notoriously difficult to bypass, if vnodebypass didn't work for you I will add HSBC UK as "no known bypasses".

**Comment by Auraaaaaaaa** [comment]
VNODEBYPASS worked fine for me!

Charlie H

**Comment by beer-psi** [comment]
Solved by commit df366c31f7064913ac6045fe8690ef1f7f3f9287.
