### ISSUE TITLE
[Request]: Kuwait Mobile ID

### ISSUE THREAD

**Issue by amrfoudaas** [joshuah345/iosjbdetectold#7]
### App to request

Kuwait Mobile ID

### App Store link

https://apps.apple.com/us/app/kuwait-mobile-id-%D9%87%D9%88%D9%8A%D8%AA%D9%8A/id1449712307

### App version

1.9.0

### Jailbreak

Unc0ver

### Bypass tried

I tried all available tweaks 

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
![bypass list](https://share.beerpsi.me/raw/hvb0cr96.png)

Did you try all of these bypasses? If you have and none is working, I'll have to add the app as `no bypass known`.

**Comment by joshuah345** [comment]
Kuwait Mobile ID currently doesn't have a bypass. Added to list.
