### ISSUE TITLE
[Request]: My Ooredoo Kuwait

### ISSUE THREAD

**Issue by amrfoudaas** [joshuah345/iosjbdetectold#9]
### App to request

My Ooredoo

### App Store link

https://apps.apple.com/us/app/my-ooredoo-kuwait/id549770639

### App version

9.4.0

### Jailbreak

Unc0ver

### Bypass tried

I have tried all available tweaks 

### Checklist before submission

- [X] The app is missing from the table, or bypasses are not working anymore.
- [X] I have checked through all open issues and none matched my app.

**Comment by beer-psi** [comment]
![bypass list](https://share.beerpsi.me/raw/hvb0cr96.png)

Did you try all of these bypasses? If you have and none is working, I'll have to add the app as `no bypass known`.

**Comment by joshuah345** [comment]
Hestia, A-Bypass, Shadow all work (unc0ver)
